### ISSUE TITLE
ghi broken: issue.rb:6:in `initialize': undefined method `[]'

### ISSUE THREAD

**Issue by eugeneware** [stephencelis/ghi#20]
ghi completely broken on my system. 

I'm running the latest snow leopard: 10.6.2

Ruby Version: ruby 1.8.7 (2008-08-11 patchlevel 72) [universal-darwin10.0]

Steps to reproduce:

```
    $ git clone git@github.com:nharbour/git-deploy.git
    $ cd git-deploy
    $ ghi
```

Gives the following error:

```
    # Open issues on nharbour/git-deploy
    /Library/Ruby/Gems/1.8/gems/ghi-0.2.4/lib/ghi/issue.rb:6:in `initialize': undefined method `[]' for #<YAML::Object:0x10171de30> (NoMethodError)
            from /Library/Ruby/Gems/1.8/gems/ghi-0.2.4/lib/ghi/api.rb:28:in `new'
            from /Library/Ruby/Gems/1.8/gems/ghi-0.2.4/lib/ghi/api.rb:28:in `list'
            from /Library/Ruby/Gems/1.8/gems/ghi-0.2.4/lib/ghi/api.rb:28:in `map'
            from /Library/Ruby/Gems/1.8/gems/ghi-0.2.4/lib/ghi/api.rb:28:in `list'
            from /Library/Ruby/Gems/1.8/gems/ghi-0.2.4/lib/ghi/cli.rb:460:in `list'
            from /Library/Ruby/Gems/1.8/gems/ghi-0.2.4/lib/ghi/cli.rb:248:in `run!'
            from /Library/Ruby/Gems/1.8/gems/ghi-0.2.4/lib/ghi/cli.rb:239:in `parse!'
            from /Library/Ruby/Gems/1.8/gems/ghi-0.2.4/bin/ghi:6
            from /usr/bin/ghi:19:in `load'
            from /usr/bin/ghi:19
```

http://pastie.org/780719

API works fine through CURL:

```
    curl http://github.com/api/v2/yaml/issues/list/nharbour/git-deploy/open
    --- 
    issues: 
    - !ruby/object:Issue 
      attributes: 
        votes: "0"
        number: "1"
        position: "1"
        issue_comments_count: "0"
        created_at: 2010-01-16 04:20:11
        title: my title
        body: test
        updated_at: 2010-01-16 04:20:11
        id: "113989"
        user_id: "38154"
        closed_at: 
        repository_id: "84647"
        state: open
      attributes_cache: {}

    - !ruby/object:Issue 
      attributes: 
        votes: "0"
        number: "2"
        position: "2"
        issue_comments_count: "0"
        created_at: 2010-01-16 04:29:38
        title: second issue
        body: boo
        updated_at: 2010-01-16 04:29:38
        id: "113995"
        user_id: "38154"
        closed_at: 
        repository_id: "84647"
        state: open
      attributes_cache: {}
```
